title: MaxBlo.ga
description: My Personal Blog
author: Hristo Jelev
logo: https://maxblo.ga/images/avatar2.jpg
github: https://github.com/hjelev
about: 

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: 
google_analytics: 


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
